import Head from 'next/head'
import Image from 'next/image'
// import { Breadcrumb, IBreadcrumbItem, IDividerAsProps } from '@fluentui/react/lib/Breadcrumb';
import { initializeIcons } from '@fluentui/react/lib/Icons';
// import { Icon } from '@fluentui/react/lib/Icon';
import PivotTabs from './components/PivotTabs'; 
import styles from '../styles/Home.module.css';

initializeIcons(undefined, { disableWarnings: true });

// const items: IBreadcrumbItem[] = [
//   // { text: 'Files', key: 'Files', onClick: _onBreadcrumbItemClicked },
//   // { text: 'Folder 1', key: 'f1', onClick: _onBreadcrumbItemClicked },
//   // { text: 'Folder 2', key: 'f2', onClick: _onBreadcrumbItemClicked },
//   // { text: 'Folder 3', key: 'f3', onClick: _onBreadcrumbItemClicked },
//   { text: 'Folder 4', key: 'f4', onClick: _onBreadcrumbItemClicked, isCurrentItem: true },
// ];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div id={styles.banner}>
          <PivotTabs></PivotTabs>
        </div>

        {/* <Breadcrumb
        items={items}
        maxDisplayedItems={10}
        ariaLabel="Breadcrumb with items rendered as buttons"
        overflowAriaLabel="More links"
      /> */}

        <h1 className={styles.title}>
          <a href="https://github.com/Ranada/nextjs_dashboard">
            Next.js Dashboard
          </a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// function _onBreadcrumbItemClicked(ev: React.MouseEvent<HTMLElement>, item: IBreadcrumbItem): void {
//   console.log(`Breadcrumb item with key "${item.key}" has been clicked. ${ev.toString()}`);
// }