import Head from 'next/head'
import Image from 'next/image'
// import { Breadcrumb, IBreadcrumbItem, IDividerAsProps } from '@fluentui/react/lib/Breadcrumb';
import { initializeIcons } from '@fluentui/react/lib/Icons';
// import { Icon } from '@fluentui/react/lib/Icon';
import AppBar from './components/AppBar';
import { DetailsListDocumentsExample } from './components/DetailsList';
import styles from '../styles/Home.module.css';
import BreadCrumbs from './components/BreadCrumbs';

initializeIcons(undefined, { disableWarnings: true });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppBar />
        <div className={styles.breadcrumbs}>
          <BreadCrumbs />
        </div>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h1>Title</h1>
            <p className={styles.description}>
              Description of contents.
            </p>
            <DetailsListDocumentsExample />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}