import Head from 'next/head'
import Image from 'next/image'
// import { Breadcrumb, IBreadcrumbItem, IDividerAsProps } from '@fluentui/react/lib/Breadcrumb';
import { initializeIcons } from '@fluentui/react/lib/Icons';
// import { Icon } from '@fluentui/react/lib/Icon';
import AppBar from './components/AppBar';
import { DetailsListDocumentsExample } from './components/DetailsList';
import styles from '../styles/Home.module.css';
import BreadCrumbs from './components/BreadCrumbs';

initializeIcons(undefined, { disableWarnings: true });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppBar />
        <div className={styles.breadcrumbs}>
          <BreadCrumbs />
        </div>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h1>Title</h1>
            <p className={styles.description}>Description of contents.</p>
            <DetailsListDocumentsExample />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Image
            src="/images/logo-blue.svg" // Route of the image file
            height={28} // Desired size with correct aspect ratio
            width={28} // Desired size with correct aspect ratio
            alt="neil ranada logo blue"
          />
        </span>
        <p>Developed by{" Neil Ranada, Software Engineer | UX"}</p>
        <span className={styles.contact}>
          <a
            href="https://github.com/Ranada"
            target="_blank"
            rel="noopener noreferrer"
          >
            <p>GitHub</p>
          </a>
          <a
            href="https://www.linkedin.com/in/neilranada/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <p>LinkedIn</p>
          </a>
        </span>
      </footer>
    </div>
  );
}